sudo: required
services:
  - docker
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
env:
  - COMPOSE_FILE=docker-compose.yml

install:
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-ce
  - sudo pip install docker-compose

before_script:
  - docker version
  - docker-compose --version
  - docker-compose up -d db
  - echo "SECRET_KEY = '1234'" >> axbot/axbot/settings/dev.py
  - docker-compose build --pull --build-arg PYTHON_VERSION="${TRAVIS_PYTHON_VERSION:-3.7}" web
  - docker-compose run --rm db psql -h db -U postgres -c "CREATE DATABASE axbot;"
  - docker-compose up -d
  - docker-compose logs

script:
  - docker-compose run --rm web sh -c "pip install pytest-django pylama > /dev/null && pytest --create-db --migrations --pylama -s"
  - docker-compose run --rm web sh -c "./manage.py reset_db --noinput > /dev/null; ./manage.py makemigrations --check"
  - docker-compose run --rm web sh -c "pip install isort > /dev/null && isort --recursive --check-only --diff"
