version: '3'

services:
  db:
    image: postgres:10.3
  memcached:
    image: memcached:1.5
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/var/www/static/
    ports:
      - "127.0.0.1:8000:80"
    depends_on:
      - django
  django:
    build: .
    command:
      - bash
      - ../entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=axbot.settings.deploy
    volumes:
      - static_files:/var/www/static/
    depends_on:
      - db
      - memcached

volumes:
  static_files:
